version: '3'
services:
  db:
    container_name: postgres_database
    image: postgres:14.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sample_user
      POSTGRES_PASSWORD: sample_password